#!/bin/bash --login
#SBATCH -p multicore
#SBATCH -n 8
#SBATCH -t 2-0

#SBATCH --mail-type=ALL
#SBATCH --mail-user=ahmad.binahmadazmi@student.manchester.ac.uk

module purge
module load gcc/14.2.0
module load openmpi

mpirun -np 8 vampire-parallel