#!/bin/bash --login
#SBATCH -p himem        # Job will use 1 core for each task
#SBATCH --mem=64G
#SBATCH -t 4-0          # Each task has a maximum 4-day (0 hours) runtime
#SBATCH -a 0-8          # Only 10 tasks in this example!

# A bash array of my 10 input parameters
X_PARAM=( 0 100 200 300 400 500 600 700 800 )

# But we started the task id at zero so we can simply do
INDEX=${SLURM_ARRAY_TASK_ID}

# Run the app with one of the parameters
./vampire_serial --input-file input_${X_PARAM[$INDEX]} --output-file output_${X_PARAM[$INDEX]}
